SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BASE_SALES_PROMOTION](
	[CODE] [nchar](10) COLLATE Chinese_PRC_CI_AS NOT NULL,
	[NAME] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[DEPARTMENT_CODE] [varchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[PROPERTY1] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[PROPERTY2] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[PROPERTY3] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[PROPERTY4] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[PROPERTY5] [nvarchar](255) COLLATE Chinese_PRC_CI_AS NULL,
	[STATUS_FLAG] [int] NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[CREATE_USER] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[CREATE_DATE_TIME] [datetime] NULL,
	[LAST_UPDATE_USER] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[LAST_UPDATE_TIME] [datetime] NULL,
 CONSTRAINT [PK_BASE_SALES_PROMOTION] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF