CREATE VIEW [dbo].[sar_sales_order_info_view]
AS
SELECT     CONVERT(char(10), BSO.CREATE_DATE_TIME, 126) AS CREATE_DATE_TIME, BSO.QUANTITY, BSO.AMOUNT, BSO.DEPARTMENT_CODE, BD.PARENT_CODE, 
                      BP.GROUP_CODE, BSO.SALES_EMPLOYEE
FROM         dbo.SAR_SALES_ORDER AS BSO LEFT OUTER JOIN
                      dbo.BASE_DEPARTMENT AS BD ON BD.CODE = BSO.DEPARTMENT_CODE LEFT OUTER JOIN
                      dbo.BASE_PRODUCT AS BP ON BP.CODE = BSO.PRODUCT_CODE

GO