CREATE VIEW [dbo].[base_sales_promotion_view]
AS
SELECT     BP.CODE, BP.NAME, BP.DEPARTMENT_CODE, BP.PROPERTY1, BP.PROPERTY2, BP.PROPERTY3, BP.PROPERTY4, BP.PROPERTY5, BP.STATUS_FLAG, 
                      BP.START_TIME, BP.END_TIME, BP.CREATE_USER, BP.CREATE_DATE_TIME, BP.LAST_UPDATE_USER, BP.LAST_UPDATE_TIME, 
                      BD.NAME AS DEPARTMENT_NAME, BD.PARENT_CODE, BU2.TRUE_NAME AS LAST_UPDATE_NAME, BU1.TRUE_NAME AS CREATE_USER_NAME
FROM         dbo.BASE_SALES_PROMOTION AS BP LEFT OUTER JOIN
                      dbo.BASE_DEPARTMENT AS BD ON BD.CODE = BP.DEPARTMENT_CODE LEFT OUTER JOIN
                      dbo.BASE_USER AS BU1 ON BU1.USER_ID = BP.CREATE_USER LEFT OUTER JOIN
                      dbo.BASE_USER AS BU2 ON BU2.USER_ID = BP.LAST_UPDATE_USER

GO