//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutLookPanl.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutLookPanl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NavigateBar {
            get {
                object obj = ResourceManager.GetObject("NavigateBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NoImage {
            get {
                object obj = ResourceManager.GetObject("NoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Add or Remove Button 的當地語系化字串。
        /// </summary>
        internal static string TEXT_ADD_OR_REMOVE_BUTTON {
            get {
                return ResourceManager.GetString("TEXT_ADD_OR_REMOVE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string TEXT_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hide 的當地語系化字串。
        /// </summary>
        internal static string TEXT_BUTTON_HIDE {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_HIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move Down 的當地語系化字串。
        /// </summary>
        internal static string TEXT_BUTTON_MOVE_DOWN {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_MOVE_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move Up 的當地語系化字串。
        /// </summary>
        internal static string TEXT_BUTTON_MOVE_UP {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_MOVE_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        internal static string TEXT_BUTTON_OK {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reset 的當地語系化字串。
        /// </summary>
        internal static string TEXT_BUTTON_RESET {
            get {
                return ResourceManager.GetString("TEXT_BUTTON_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Collapse 的當地語系化字串。
        /// </summary>
        internal static string TEXT_COLLAPSE_BUTTON_COLLAPSE {
            get {
                return ResourceManager.GetString("TEXT_COLLAPSE_BUTTON_COLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Expand 的當地語系化字串。
        /// </summary>
        internal static string TEXT_COLLAPSE_BUTTON_EXPAND {
            get {
                return ResourceManager.GetString("TEXT_COLLAPSE_BUTTON_EXPAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Configure Buttons 的當地語系化字串。
        /// </summary>
        internal static string TEXT_CONFIGURE_BUTTONS {
            get {
                return ResourceManager.GetString("TEXT_CONFIGURE_BUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Display buttons in this order 的當地語系化字串。
        /// </summary>
        internal static string TEXT_LABEL_ORDER_DESCRIPTION {
            get {
                return ResourceManager.GetString("TEXT_LABEL_ORDER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Navigation Pane Options... 的當地語系化字串。
        /// </summary>
        internal static string TEXT_MENU_OPTIONS {
            get {
                return ResourceManager.GetString("TEXT_MENU_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Color Table 的當地語系化字串。
        /// </summary>
        internal static string TEXT_SELECT_COLOR_TABLE {
            get {
                return ResourceManager.GetString("TEXT_SELECT_COLOR_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show Fewer Buttons 的當地語系化字串。
        /// </summary>
        internal static string TEXT_SHOW_FEWER_BUTTONS {
            get {
                return ResourceManager.GetString("TEXT_SHOW_FEWER_BUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Show More Buttons 的當地語系化字串。
        /// </summary>
        internal static string TEXT_SHOW_MORE_BUTTONS {
            get {
                return ResourceManager.GetString("TEXT_SHOW_MORE_BUTTONS", resourceCulture);
            }
        }
    }
}
